### PR TITLE
Add chromatic's keys

### PR DESCRIPTION
**Pull request by chromatic**

### CODE REVIEW

**Comment by rnicoll** [comment]
Checked:

```
$ gpg2 chromatic.txt.asc
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Signature made Sat Dec 24 18:56:43 2022 GMT
gpg:                using RSA key 167A4054DB3BFCF485CA10904AAB40C819FEB076
gpg: Good signature from "chromatic <chromatic@wgz.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 167A 4054 DB3B FCF4 85CA  1090 4AAB 40C8 19FE B076
```

**Review by rnicoll — APPROVED** [review]
Verified against key from https://github.com/chromatic.gpg

**Comment by rnicoll** [comment]
Just realised - can you also sign the commit ideally? We can do it without, given the content is signed, but it's cleaner if we have signed commits.

**Comment by chromatic** [comment]
Good point. I've raised #6 instead. For some reason, pushing to my branch didn't update this PR. I can close this if you prefer.

**Comment by rnicoll** [comment]
Closed as replaced by #6

**Pull request closed without merging**
